# Generated by Django 3.0.2 on 2020-02-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regfact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('pas', models.CharField(max_length=200)),
                ('num', models.CharField(max_length=200)),
            ],
        ),
    ]
